# to configure the linter:
# - copy this file and .eslintignore at the root of the package you want to lint
# - install dependencies: npm i -D eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-prettier eslint-plugin-prettier prettier
# - add "lint": "eslint ." to the scripts in package.json
# - run `npm run lint` to lint the project
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  prettier/prettier: warn
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-unused-vars': [warn, { 'argsIgnorePattern': '^_' }]
