export const HEIGHT_CHANGE_COST = 10
export const SHAPE_CHANGE_COST = 50
export const CAGE_CHANGE_COST = 65
export const COUVETTE_CHANGE_COST = 30
export const REMELTING_MACHINE_CHANGE_COST = 1000
export const MAX_DAILY_CHANGES_VIOLATION_COST = 100
export const MAX_WEEKLY_CHANGES_VIOLATION_COST = 100
export const COOLDOWN_NOT_RESPECTED_COST = 1000000
